-- CreateTable
CREATE TABLE "Session" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "start" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "stop" DATETIME
);

-- CreateTable
CREATE TABLE "Measure" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "time" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "value" REAL NOT NULL,
    "idSession" INTEGER NOT NULL,
    CONSTRAINT "Measure_idSession_fkey" FOREIGN KEY ("idSession") REFERENCES "Session" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Container" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "type" TEXT NOT NULL,
    "numBalls" INTEGER NOT NULL,
    "idSession" INTEGER NOT NULL,
    CONSTRAINT "Container_idSession_fkey" FOREIGN KEY ("idSession") REFERENCES "Session" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
